Softmax function
=====
Logistic classifier: `WX = Y`
Scores -> Probabilities : `S(y_i) = e^(y_i) / sum( e^(y_j) )`

Cross-entropy cost function
-----
`D(S, L) = -sum( L_i * log(S_i) )`
 - `S(Y) = Y_hat`
 - `L = Y`
 
`Loss = 1/N sum( D(S(W*X_i+b), Li) )`

Gradient descent
-----
STEP = `-alpha * derivative( loss(w1, w2) )`

In [13]:
x_data = [[1., 2., 1.],
          [1., 3., 2.],
          [1., 3., 4.],
          [1., 5., 5.],
          [1., 7., 5.],
          [1., 2., 5.],
          [1., 6., 6.],
          [1., 7., 7.]]
y_data = [[0., 0., 1.],
          [0., 0., 1.],
          [0., 0., 1.],
          [0., 1., 0.],
          [0., 1., 0.],
          [0., 1., 0.],
          [0., 0., 1.],
          [0., 0., 1.]]
# x_data = [[1., 1., 1., 1., 1., 1., 1., 1.],
#           [2., 3., 3., 5., 7., 2., 6., 7.],
#           [1., 2., 4., 5., 5., 5., 6., 7.]]
# y_data = [[0., 0., 0., 0., 0., 0., 1., 1.],
#           [0., 0., 0., 1., 1., 1., 0., 0.],
#           [1., 1., 1., 0., 0., 0., 0., 0.]]

import tensorflow as tf

X = tf.placeholder("float", [None, 3])  # x1, x2 and 1 (for bias)
Y = tf.placeholder("float", [None, 3])  # A, B, C => 3 classes
W = tf.Variable(tf.zeros([3, 3]))

hypothesis = tf.nn.softmax(tf.matmul(X, W))

learning_rate = .001
cost = tf.reduce_mean(-tf.reduce_sum(Y*tf.log(hypothesis), reduction_indices=1))
optimizer = tf.train.GradientDescentOptimizer(learning_rate).minimize(cost)

init = tf.initialize_all_variables()

sess = tf.Session()
sess.run(init)

for step in xrange(2001):
    sess.run(optimizer, feed_dict={X:x_data, Y:y_data})
    if step % 200 == 0:
        print step, sess.run(cost, feed_dict={X:x_data, Y:y_data}), sess.run(W)

0 1.09151 [[ -3.33333330e-04   4.16666626e-05   2.91666656e-04]
 [ -1.45833357e-03   2.91666773e-04   1.16666686e-03]
 [ -1.45833357e-03   4.16666706e-04   1.04166684e-03]]
200 0.780599 [[-0.03302823  0.002706    0.03032222]
 [-0.1265296   0.03458844  0.0919412 ]
 [-0.1269189   0.05814527  0.06877366]]
400 0.739866 [[-0.04844064  0.00034499  0.04809566]
 [-0.17510462  0.04989799  0.12520666]
 [-0.17469139  0.09413347  0.08055794]]
600 0.721218 [[-0.05942659 -0.00417597  0.06360256]
 [-0.20712054  0.05753902  0.1495816 ]
 [-0.20532399  0.12033778  0.08498629]]
800 0.709686 [[-0.06820342 -0.00972322  0.07792662]
 [-0.23153698  0.06208384  0.16945331]
 [-0.22810657  0.14162229  0.08648437]]
1000 0.701507 [[-0.07561301 -0.01586152  0.0914745 ]
 [-0.25150681  0.06512281  0.18638413]
 [-0.24633147  0.15978576  0.08654573]]
1200 0.695243 [[-0.08207646 -0.02237551  0.10445193]
 [-0.26852417  0.06736121  0.20116307]
 [-0.26156002  0.17570314  0.08585697]]
1400 0.690207 [[-0.08783827 -0.02914042

In [14]:
a = sess.run(hypothesis, feed_dict={X: [[1, 11, 7]]})
print a, sess.run(tf.arg_max(a, 1))

b = sess.run(hypothesis, feed_dict={X: [[1, 3, 4]]})
print b, sess.run(tf.arg_max(b, 1))

c = sess.run(hypothesis, feed_dict={X: [[1, 1, 0]]})
print c, sess.run(tf.arg_max(c, 1))

all = sess.run(hypothesis, feed_dict={X: [[1, 11, 7], [1, 3, 4], [1, 1, 0]]})
print all, sess.run(tf.arg_max(all, 1))

[[  7.67555248e-05   2.51073748e-01   7.48849511e-01]] [2]
[[ 0.01594904  0.45657307  0.52747792]] [2]
[[ 0.2069089   0.3229892   0.47010192]] [2]
[[  7.67555248e-05   2.51073748e-01   7.48849511e-01]
 [  1.59490425e-02   4.56573069e-01   5.27477920e-01]
 [  2.06908897e-01   3.22989196e-01   4.70101923e-01]] [2 2 2]
