# Lab 08 - Tensor Manipulation

## 2D Array

In [1]:
import numpy as np
import tensorflow as tf

sess = tf.Session()

In [2]:
t = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])
t

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [3]:
t.ndim

2

In [4]:
t.shape

(4, 3)

## Shape, Rank, Axis

In [6]:
t = tf.constant([1, 2, 3, 4])
with sess.as_default():
    print(tf.shape(t).eval())

[4]


* 제일 안쪽이 `axis=dimension_n - 1` 또는 `axis=-1`
* 제일 바깥쪽이 `axis=0`

## Matmul vs multiply

In [15]:
mat1 = tf.constant([[1, 2], [3, 4]])
mat2 = tf.constant([[1], [2]])
print("mat1 shape", mat1.shape)
print("mat2 shape", mat2.shape)
with sess.as_default():
    print(tf.matmul(mat1, mat2).eval())

mat1 shape (2, 2)
mat2 shape (2, 1)
[[ 5]
 [11]]


In [17]:
with sess.as_default():
    print((mat1*mat2).eval())

[[1 2]
 [6 8]]


## Broadcasting

In [18]:
mat1 = tf.constant([[3, 3]])
mat2 = tf.constant([[2, 2]])
with sess.as_default():
    print((mat1+mat2).eval())

[[5 5]]


In [19]:
mat1 = tf.constant([[1, 2]])
mat2 = tf.constant(3)
with sess.as_default():
    print((mat1+mat2).eval())

[[4 5]]


In [20]:
mat1 = tf.constant([[1, 2]])
mat2 = tf.constant([3, 4])
with sess.as_default():
    print((mat1+mat2).eval())

[[4 6]]


In [21]:
mat1 = tf.constant([[1, 2]])
mat2 = tf.constant([[3], [4]])
with sess.as_default():
    print((mat1+mat2).eval())

[[4 5]
 [5 6]]


Reference : https://docs.scipy.org/doc/numpy/user/basics.broadcasting.html

## Reduce mean & Reduce sum

In [23]:
with sess.as_default():
    print(tf.reduce_mean([1, 2], axis=0).eval())

1


In [25]:
x = [[1., 2.],
     [3., 4.]]

with sess.as_default():
    print(tf.reduce_mean(x).eval())

2.5


In [26]:
with sess.as_default():
    print(tf.reduce_mean(x, axis=0).eval())

[ 2.  3.]


In [27]:
with sess.as_default():
    print(tf.reduce_mean(x, axis=1).eval())

[ 1.5  3.5]


In [28]:
with sess.as_default():
    print(tf.reduce_mean(x, axis=-1).eval())

[ 1.5  3.5]


여기서 `axis`는 연산해나가는 방향을 의미함

In [29]:
with sess.as_default():
    print(tf.reduce_sum(x).eval())
    print(tf.reduce_sum(x, axis=0).eval())
    print(tf.reduce_sum(x, axis=-1).eval())

10.0
[ 4.  6.]
[ 3.  7.]


### 많이 응용되는 expression

In [30]:
with sess.as_default():
    print(tf.reduce_mean(tf.reduce_sum(x, axis=-1)).eval())

5.0


## Argmax
가장 큰 값의 인덱스를 반환

In [33]:
x = [[0, 1, 2],
     [2, 1, 0]]

with sess.as_default():
    print(tf.argmax(x, axis=0).eval())

[1 0 0]


In [34]:
with sess.as_default():
    print(tf.argmax(x, axis=1).eval())

[2 0]


In [35]:
with sess.as_default():
    print(tf.argmax(x, axis=-1).eval())

[2 0]


## Reshape**

In [36]:
t = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

t.shape

(12,)

In [37]:
with sess.as_default():
    print(tf.reshape(t, shape=[-1, 3]).eval())

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [38]:
with sess.as_default():
    print(tf.reshape(t, shape=[-1, 1, 3]).eval())

[[[ 1  2  3]]

 [[ 4  5  6]]

 [[ 7  8  9]]

 [[10 11 12]]]


In [39]:
with sess.as_default():
    print(tf.squeeze([[0], [1], [2]]).eval())

[0 1 2]


In [40]:
with sess.as_default():
    print(tf.expand_dims([0, 1, 2], 1).eval())

[[0]
 [1]
 [2]]


## One hot

In [41]:
with sess.as_default():
    print(tf.one_hot([[0], [1], [2], [0]], depth=3).eval())

[[[ 1.  0.  0.]]

 [[ 0.  1.  0.]]

 [[ 0.  0.  1.]]

 [[ 1.  0.  0.]]]


In [42]:
t = tf.one_hot([[0], [1], [2], [0]], depth=3)
with sess.as_default():
    print(tf.reshape(t, shape=[-1, 3]).eval())

[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]
 [ 1.  0.  0.]]


## Casting

`tf.cast(value, type)`

## Stack

In [43]:
x = [1, 4]
y = [2, 5]
z = [3, 6]

with sess.as_default():
    print(tf.stack([x, y, z]).eval())

[[1 4]
 [2 5]
 [3 6]]


In [44]:
with sess.as_default():
    print(tf.stack([x, y, z], axis=1).eval())

[[1 2 3]
 [4 5 6]]


In [45]:
with sess.as_default():
    print(tf.stack([x, y, z], axis=0).eval())

[[1 4]
 [2 5]
 [3 6]]


In [46]:
with sess.as_default():
    print(tf.stack([x, y, z], axis=-1).eval())

[[1 2 3]
 [4 5 6]]


## Ones and Zeros like

In [47]:
x = [[0, 1, 2],
     [2, 1, 0]]

with sess.as_default():
    print(tf.ones_like(x).eval())
    print(tf.zeros_like(x).eval())

[[1 1 1]
 [1 1 1]]
[[0 0 0]
 [0 0 0]]


`zip(arr1, arr2)` 도 유용한 함수